[build]
builder = "nixpacks"

[build.nixpacks]
python-version = "3.12"

[deploy]
startCommand = "python manage.py migrate --noinput && python manage.py shell -c \"exec(open('seed.py').read())\" && python manage.py collectstatic --noinput && gunicorn faculflow_backend.wsgi --bind 0.0.0.0:$PORT"
