# Generated by Django 5.2.13 on 2026-05-18 14:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_post_bookmarks_post_likes_chatmessage_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='streak_freeze_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='xp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='BattlePassReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_required', models.PositiveIntegerField(unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('reward_type', models.CharField(choices=[('desconto', 'Desconto na Mensalidade'), ('horas', 'Horas Extracurriculares'), ('brinde', 'Brinde Físico')], default='brinde', max_length=20)),
                ('icon', models.CharField(default='🎁', max_length=10)),
                ('claimed_by', models.ManyToManyField(blank=True, related_name='claimed_rewards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['level_required'],
            },
        ),
    ]
